name: Github actions build and deploy Demo

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: Build & Deploy to GitHub Pages
      uses: BryanSchuetz/jekyll-deploy-gh-pages@1.0
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build
        BUILD_SCRIPT: npm install && npm run build

